#env: "local" #local, dev, prod
#storage_conn: "user=postgres password=postgres dbname=url-shortener host=localhost port=5432 sslmode=disable"
#http_server:
#  address: "localhost:8080"
#  timeout: 4s
#  idle_timeout: 60s
#jwt:
#  secret_key: "samyisecretkey"
env: "local"
database:
  host: localhost
  port: 5432
  name: book_base
  user: postgres
  password: 1977
http_server:
  address: "localhost:8083"
  timeout: 4s
  idle_timeout: 60s
jwt:
  secret_key: fdhjaskhHASUSDFGHUGUhsdfgj312HJFldshUl