env: "local"
storage_conn: "user=postgres password=postgres dbname=flowers host=localhost port=5432 sslmode=disable"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
jwt:
  secret_key: "secretkey"